AWSTemplateFormatVersion: 2010-09-09
Description: template for RDS / Application Layer

Parameters:
  VPCStack:
    Type: String
    Default: cfn-vpc
  SGStack:
    Type: String
    Default: cfn-securitygroup
  DBUser:
    Type: String
    Default: admin
    NoEcho: true
  DBPassword:
    Type: String
    Default: raiseTechDem0!
    NoEcho: true

Resources:
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBInstanceIdentifier: cfn-rds
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      AvailabilityZone: !Select [0, !GetAZs ]
      MultiAZ: false
      PubliclyAccessible: false
      Engine: mysql
      EngineVersion: 8.0.32
      StorageType: gp2
      StorageEncrypted: true
      CopyTagsToSnapshot: true
      EnablePerformanceInsights: false
      DeletionProtection: false
      BackupRetentionPeriod: 0
      DBSubnetGroupName: !Ref RDSDBSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${SGStack}-RDS-MySQL

  RDSDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet Group for Private Subnet
      DBSubnetGroupName: !Sub ${AWS::StackName}-private-subnetgroup
      SubnetIds:
        - Fn::ImportValue: !Sub ${VPCStack}-PrivateSubnet1a
        - Fn::ImportValue: !Sub ${VPCStack}-PrivateSubnet1c

Outputs:
  RDSDBEndpoint:
    Value: !GetAtt RDSDBInstance.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-RDSDBEndpoint
